### ISSUE TITLE
Storybook v7

### ISSUE THREAD

**Issue by Sephyr0s** [jimdrury/storybook-addon-badges#11]
Hi,

Thanks for all the work developing this plugin.

at my place we decided to already upgrade to Storybook v7 due to better Vue support. We're wondering if there are already plans here to make the plugin ready for Storybook 7. Considering it's already on release candidates I doubt there will be any big changes.

From the migrations notes

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#70-core-addons-changes
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#70-addon-authors-changes

**Comment by jimdrury** [comment]
Hey,
I'm super open to making this Storybook 7 safe, i'll see what I can do over the bank holiday weekend

**Comment by jimdrury** [comment]
Hey folks, i've pushed a canary release [2.0.0--canary.12.aa9de47.0](https://www.npmjs.com/package/@geometricpanda/storybook-addon-badges/v/2.0.0--canary.12.aa9de47.0)

You can install this using 
```sh
npm install @geometricpanda/storybook-addon-badges@2.0.0--canary.12.aa9de47.0
```
or 
```sh
yarn add @geometricpanda/storybook-addon-badges@2.0.0--canary.12.aa9de47.0
```

Could I trouble you to test in your environments please?
Once I've had a few folks say they're happy with it then i'll cut 2.0.0

It's not really a breaking change, but thought best to mark it as due to the Storybook Preview pattern changing.

**Tested in**
- [x] Angular
- [x] React
- [x] Vue

**Notes**
When testing Angular, I got some warnings about `prettier` & `react-textarea-autosize`, I'm assuming this is Storybook 7 Angular issue as I dont use either of them in the distribution.

**Comment by tommiv** [comment]
@geometricpanda Canary release compiles without warnings && works as intended in SB v7.0.2 with Vue v2:

![image](https://user-images.githubusercontent.com/789246/230907822-560d54b2-5fad-4ee6-b0c3-01e62e15b52b.png)

**Comment by Sephyr0s** [comment]
Works like a charm! Question though, since in Storybook 7 they seperated docs and canvas different, is it possible to show the badges on the docs page? Or do I need to make a new enhancement request for this?

Thanks for the good work!

<img width="167" alt="image" src="https://user-images.githubusercontent.com/34128667/230988272-aafe5d1e-f6be-4bae-a7d6-6b0b458b7730.png">

**Comment by jimdrury** [comment]
@Sephyr0s Yeah i noticed that, i'll keep looking into it, but thanks to you and @tommiv for testing - i'll release 2.0.0 now
