### ISSUE TITLE
Showing Badges in Sidebar Labels

### ISSUE THREAD

**Issue by platzhersh** [jimdrury/storybook-addon-badges#17]
This is a feature request.

Are there any plans to allow showing the badges in the labels of the stories in the sidebar as well?

I saw this for mui for example:
![image](https://github.com/geometricpanda/storybook-addon-badges/assets/1445827/27bd605f-2ca1-4665-91c6-d03cae17b026)

Currently, this is not possible from what I see, so we would just use the sidebar roots to put the components with the same badges in their own group.

![image](https://github.com/geometricpanda/storybook-addon-badges/assets/1445827/c2836977-cc74-4032-bd1c-b85ce823c8f2)

**Comment by jimdrury** [comment]
Hey!
You're not the first person who's asked for this, so you're in good company. 

Last time I looked, it seemed almost possible, I'll have a dig around to see if that's changed.

**Comment by shilman** [comment]
Hi @geometricpanda I did a very dirty prototype of what this might look like in a v7+ compatible way here https://github.com/shilman/storybook-tag-badges

Tags have been around since 7.0 but not really utilized in user facing features. The upcoming 8.1 release will have some tags features like statically & interactively filtering the sidebar. It would be great to also be able to highlight an upgraded version of this addon based on tags, since I see lots of high quality storybooks that rely on it it.

If you'd be interested in upgrading the addon to use tags, I can potentially rework core bits of storybook to help make it easier/better.

**Comment by Sidnioulz** [comment]
Hey folks.

Just to confirm this is possible only on stories that have already been loaded. See the screenshots. Within the sidebar label renderer, we have access to story parameters _if_ they are loaded, but we always have access to tags.

Switching to rendering tags as badges, like @shilman suggested, would allow this feature to work.

![image](https://github.com/user-attachments/assets/0c33449b-9a59-4d8d-9074-f5810d435bee)
![image](https://github.com/user-attachments/assets/076671b4-26e2-4032-8666-ddf843f2336e)

**Comment by Sidnioulz** [comment]
Code is here: https://github.com/geometricpanda/storybook-addon-badges/commit/c0fa99659b9e5571a49d7b5985192bfed2002f51

**Comment by jimdrury** [comment]
@Sidnioulz , i really like that, i'm incorporating that now

**Comment by tibuurcio** [comment]
I'm trying to accomplish the use case highlighted by @Sidnioulz but can't seem to figure it out how 🤔 

Any change in docs needed? I'll keep investigating and open a PR if I can figure it out :)

**Comment by Sidnioulz** [comment]
Hi @tibuurcio!

You cannot get this kind of rendering on every sidebar item with this addon, because it uses story `parameters` as a source of data. Storybook does not provide `parameters` in the sidebar (for performance reasons), and that's a fundamental limitation of the product that will not change in the future.

A solution is to draw badges based on tags instead of story `parameters`, because tags are available in more contexts. 

Here are ways to do that:
* https://gist.github.com/jpzwarte/b7cc6cc1aa2ca03b288c42bef823e344
* https://github.com/shilman/storybook-tag-badges

I recently wrote https://github.com/Sidnioulz/storybook-addon-tag-badges specifically to address this need. That addon is only for SB 8.4+, as it relies on new features we've introduced around tags in SB 8.4. There are plenty of things that @geometricpanda's addon does better, and my own addon will never support per-story config because of the same limitation. Going forward, you get to choose which limitations you prefer to have and you have a ready-made solution either way :)
